### ISSUE TITLE
Doc: latest version has no `--overwrite` anymore

### ISSUE THREAD

**Issue by maxhbr** [carderne/signal-export#132] opened 2024-07-14 11:21 UTC
Might be good to fix that:

https://github.com/carderne/signal-export/blob/6a5f7ef646c0422963abefe59a1611b93a89b673/README.md?plain=1#L164

**Comment by carderne** [comment] 2024-07-14 12:22
Thanks for spotting!
The default behaviour is now just to never overwrite, which feels safer and made for slightly simpler code.

Out of interest: do you think the option should come back, or are you just reporting the out-of-date README?

**Comment by carderne** [comment] 2024-07-14 13:51
Anyway I put it back:
https://github.com/carderne/signal-export/releases/tag/v2.3.6

**Comment by maxhbr** [comment] 2024-07-17 14:22
the `--overwrite` now seems to append or merge the histories.

**Comment by carderne** [comment] 2024-07-17 14:42
Yeah that's why I took it away in the first place...

Options:
1. Just write but don't go out of its way to delete anything (CURRENT BEHAVIOUR)
2. Explicitly delete delete and recreate the target directory: I guess this is what user's expect, I was just nervous of doing too much destructive stuff
3. No overwrite option. This is what I briefly had, but the option is actually needed for manual Docker export due to permissions stuff.

I assume you're saying (2) is the way to go?

**Comment by maxhbr** [comment] 2024-07-17 14:49
I would have expected 2, yes

**Comment by carderne** [comment] 2024-07-27 21:44
Updated to match your expected behaviour here:
https://github.com/carderne/signal-export/commit/8f71f4e2dda6a545d3a74c91c9454048e18c2160

Released in v2.3.7

**Closed by carderne** 2024-07-27 21:44 UTC
